export const USER_COMMENT_POST = 'USER_COMMENT_POST';
export const USER_REVIEW_POST = 'USER_REVIEW_POST';
export const AUTHOR_POST_NEW_CHAPTER = 'AUTHOR_POST_NEW_CHAPTER';
export const USER_FOLLOW_AUTHOR = 'USER_FOLLOW_AUTHOR';
export const ADMIN_DISABLED_POST = 'ADMIN_DISABLED_POST';
